services:
  - type: web
    name: smart-contract-vul-detect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production

